spring:
  application:
    name: TestDocker
---
spring:
  config:
    activate:
      on-profile: green
server:
  port: 9000
---
spring:
  config:
    activate:
      on-profile: blue
server:
  port: 9001